Agenda/Controllers/AgendaController.cs
using Agenda.data.Models.Domain;
using Agenda.data.Repository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Agenda.Controllers
{
    public class AgendaController : Controller
    {
        private readonly ITarefasRepository _tarefasRepo;
        public AgendaController(ITarefasRepository tarefasRepo) 
        {
            _tarefasRepo = tarefasRepo;
        }

        #region Create


        public async Task<IActionResult> Criar()
        {
            return View();
        }

        public async Task<IActionResult> Estatistica()
        {
            {
                var tasks = await _tarefasRepo.ListarAsync();

                return View(tasks.OrderByDescending(x => x.Data));
            }
        }


        [HttpPost]
        public async Task<IActionResult> SalvarTarefa(Tarefas tarefas)
        {
            try
            {
                if (!ModelState.IsValid)
                    return View(tarefas);

                if (tarefas.Data.Year < DateTime.Now.Year || tarefas.Data.Month < DateTime.Now.Month || tarefas.Data.Day < DateTime.Now.Day)
                    throw new Exception("Data inválida");

                    if (tarefas.hora_inicio > tarefas.hora_fim)
                    throw new Exception("Hora inválida");

                if (tarefas.hora_fim.Hour - tarefas.hora_inicio.Hour > 5)
                    throw new Exception("Tarefa deve ter menos de 5 hora de duração");
              
                bool criarTarefa = await _tarefasRepo.CriarAsync(tarefas);
                if (criarTarefa)
                    TempData["msg"] = "Tarefa adicionada com sucesso";
                else
                   TempData["msg"] = "Tarefa não adicionada";
            }
            catch (Exception ex)
            {
                TempData["msg"] = 
                     ex.Message;
            }
            return RedirectToAction(nameof(Listar));
        }
        #endregion

        #region Read
        public async Task<IActionResult> Listar()
        
        {
            var tasks = await _tarefasRepo.ListarAsync();

            return View(tasks.OrderByDescending(x => x.Data));
        }
        #endregion

        #region Update
        public async Task<IActionResult> Editar(int id)
        {
            if (id == 0)
            {
                TempData["msg"] = "Tarefa não encontrada.";

                return RedirectToAction("Listar");
            }

            var task = await _tarefasRepo.GetTarefasAsync(id);
            return View(task);
        }

        [HttpPost]
        public async Task<IActionResult> EditarTarefa(Tarefas tarefas)
        { 
           try
           {   
                if (!ModelState.IsValid)
                    return RedirectToAction("Editar", tarefas.Id);

                if (tarefas.Data.Year < DateTime.Now.Year || tarefas.Data.Month < DateTime.Now.Month || tarefas.Data.Day < DateTime.Now.Day)
                    throw new Exception("Data inválida");

                if (tarefas.hora_inicio > tarefas.hora_fim)
                    throw new Exception("Hora inválida");

                if (tarefas.hora_fim.Hour - tarefas.hora_inicio.Hour > 5)
                    throw new Exception("Tarefa deve ter menos de 5 hora de duração");

               var tarefaEditada = await _tarefasRepo.EditarAsync(tarefas);
                    if (tarefaEditada)
                        TempData["msg"] = "Editada com sucesso";
                    else
                        TempData["msg"] = "Não pode ser editada";

           }
           catch (Exception ex)
           {
                TempData["msg"] = ex.Message;
           }
           
            return RedirectToAction("Listar");
        }
        #endregion

        #region Delete
        public async Task<IActionResult> Excluir(int id)
        {
            var deleteTask = await _tarefasRepo.DeletarAsync(id);
            return RedirectToAction(nameof(Listar));
        }
        #endregion

    }
}

Agenda/Views/Agenda/Criar.cshtml
@model Agenda.data.Models.Domain.Tarefas;

<h3>Criar Tarefa</h3>

<a asp-action="Listar" asp-controller="Agenda" class="btn btn-primary">Lista de Tarefas</a>

<form action="/Agenda/SalvarTarefa" method="post">
    <div class="mb-3">
        <label asp-for="Titulo" class="form-label">Título</label>
        <input required asp-for="Titulo" type="text" class="form-control">

    </div>

    <div class="mb-3">
        <label asp-for="Descricao" class="form-label">Descrição</label>
        <textarea required asp-for="Descricao" class="form-control"></textarea>

    </div>

    <div class="mb-3">
        <label  asp-for="Data" class="form-label">Data</label>
        <input required asp-for="Data" type="date" class="form-control">

    </div>

    <div class="mb-3">
        <label asp-for="Prioridade" class="form-label">Prioridade</label>
        <select asp-for="Prioridade" class="form-control">
            <option value="Alta">Alta</option>
            <option value="Média">Média</option>
            <option value="Baixa">Baixa</option>
        </select>
    </div>

    <div class="mb-3">
        <label  asp-for="hora_inicio" class="form-label">Hora de início</label>
        <input required asp-for="hora_inicio" type="time" class="form-control">

    </div>

    <div class="mb-3">
        <label asp-for="hora_fim" class="form-label">Hora de Término</label>
        <input required asp-for="hora_fim" type="time" class="form-control">

    </div>

    @if (TempData["msg"] != null)
    {
        <div class="bg-warning mb-3">
            @TempData["msg"]
        </div>
    }

    <div class="mb-3">
        <button type="submit" class="btn btn-primary">Adicionar Tarefa</button>
    </div>
    
</form>

Agenda/Views/Agenda/Editar.cshtml
@model Agenda.data.Models.Domain.Tarefas;

<h3>Editar Tarefa</h3>

<a asp-action="Listar" asp-controller="Agenda" class="btn btn-primary">Lista de Tarefas</a>

<form asp-action="EditarTarefa" asp-controller="Agenda" method="post">
    <input asp-for="Id" type="hidden" class="form-control">

    <div class="mb-3">
        <label asp-for="Titulo" class="form-label">Título</label>
        <input asp-for="Titulo" type="text" class="form-control">
        <span class="text-danger" asp-validation-for="Titulo"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Descricao" class="form-label">Descrição</label>
        <textarea asp-for="Descricao" class="form-control"></textarea>
        <span class="text-danger" asp-validation-for="Descricao"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Data" class="form-label">Data</label>
        <input asp-for="Data" type="date" class="form-control">
        <span class="text-danger" asp-validation-for="Data"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Prioridade" class="form-label">Prioridade</label>
        <select asp-for="Prioridade" class="form-control">
            <option value="1">Alta</option>
            <option value="2">Média</option>
            <option value="3">Baixa</option>
        </select>
    </div>

    <div class="mb-3">
        <label asp-for="Finalizada" class="form-label">Finalizada</label>
        <select asp-for="Finalizada" class="form-control">
            <option value="@true">Sim</option>
            <option value="@false">Não</option>
        </select>
    </div>

    <div class="mb-3">
        <label asp-for="hora_inicio" class="form-label">Hora de início</label>
        <input asp-for="hora_inicio" type="time" class="form-control">
        <span class="text-danger" asp-validation-for="hora_inicio"></span>
    </div>

    <div class="mb-3">
        <label asp-for="hora_fim" class="form-label">Hora de Término</label>
        <input asp-for="hora_fim" type="time" class="form-control">
        <span class="text-danger" asp-validation-for="hora_fim"></span>
    </div>

    @if (TempData["msg"] != null)
    {
        <div class="bg-warning mb-3">
            @TempData["msg"]
        </div>
    }

    <div class="mb-3">
        <button type="submit" class="btn btn-success">Salvar</button>
    </div>

</form>

Agenda/Views/Agenda/Estatistica.cshtml
@using Agenda.data.Models.Domain;

@model IEnumerable<Tarefas>

@{

    DateTime? dataInicioFiltro = null;
    DateTime? dataFimFiltro = null;

    if (Context.Request.Query.ContainsKey("dataInicio") && Context.Request.Query.ContainsKey("dataFim"))
    {
        dataInicioFiltro = DateTime.TryParse(Context.Request.Query["dataInicio"], out var dataInicio) ? dataInicio : (DateTime?)null;
        dataFimFiltro = DateTime.TryParse(Context.Request.Query["dataFim"], out var dataFim) ? dataFim : (DateTime?)null;

        if (dataInicioFiltro == null || dataFimFiltro == null)
        {
            <div class="alert alert-danger">Por favor, insira datas válidas para o filtro.</div>
            dataInicioFiltro = null;
            dataFimFiltro = null;
        }
    }

    var tarefasFiltradas = Model.Where(t =>
        (!dataInicioFiltro.HasValue || t.Data.Date >= dataInicioFiltro.Value.Date) &&
        (!dataFimFiltro.HasValue || t.Data.Date <= dataFimFiltro.Value.Date));

    var tarefasAgrupadasPorData = tarefasFiltradas.GroupBy(t => t.Data.Date);
}

<div class="container mt-5">
    <div class="p-3">
        <h1>Minhas Estatísticas</h1>
        @if (Model != null)
        {
            <h2>Você possui @Model.Count() tarefas cadastradas</h2>
            <h3>Você concluiu @Model.Count(t => t.Finalizada) tarefas</h3>
        }

        <a asp-action="Listar" asp-controller="Agenda" class="btn btn-primary">Lista de Tarefas</a>
    </div>

    <form method="get">
        <div class="form-group">
            <label for="dataInicio">Data de Início:</label>
            <input type="date" id="dataInicio" name="dataInicio" value="@dataInicioFiltro?.ToString("yyyy-MM-dd")" class="form-control" required>
        </div>
        <div class="form-group">
            <label for="dataFim">Data de Fim:</label>
            <input type="date" id="dataFim" name="dataFim" value="@dataFimFiltro?.ToString("yyyy-MM-dd")" class="form-control" required>
        </div>
        <button type="submit" class="btn btn-primary">Filtrar</button>
    </form>

    <table class="table table-stripped mt-3">
        <thead>
            <tr>
                <th>Data</th>
                <th>Total de Tarefas</th>
                <th>Total de Horas</th>
                <th>Média de Horas</th>
                <th>Percentual Concluído</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var grupo in tarefasAgrupadasPorData)
            {
                var data = grupo.Key;
                var totalTarefas = grupo.Count();
                var totalTarefasConcluidas = grupo.Count(tarefa => tarefa.Finalizada);
                var totalHoras = grupo.Sum(tarefa => (tarefa.hora_fim - tarefa.hora_inicio).TotalHours);
                var mediaHoras = totalTarefas > 0 ? totalHoras / totalTarefas : 0;
                var percentualConcluido = totalTarefas > 0 ? (double)totalTarefasConcluidas / totalTarefas * 100 : 0;

                <tr>
                    <td>@data.ToShortDateString()</td>
                    <td>@totalTarefas</td>
                    <td>@totalHoras</td>
                    <td>@mediaHoras</td>
                    <td>@percentualConcluido%</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Agenda/Views/Agenda/Excluir.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

Agenda/Views/Agenda/Listar.cshtml
@using Agenda.data.Models.Domain;
@model IEnumerable<Tarefas>

<div class="container mt-5">
    <h1>Minha Agenda</h1>
    <div class="p-3">
        @if (Model != null && Model.Any()) 
        {
            <a class="btn btn-primary" asp-action="criar" asp-controller="Agenda">Nova Tarefa</a>
            <a class="btn btn-primary" asp-action="estatistica" asp-controller="Agenda">Minhas Estatísticas</a>
        }
    </div>

    @if (Model != null && Model.Any()) 
    {
        <table class="table table-stripped">
            <thead>
                <tr>
                    <th>Título da tarefa</th>
                    <th>Descrição da tarefa</th>
                    <th>Data</th>
                    <th>Hora início</th>
                    <th>Hora fim</th>
                    <th>Prioridade</th>
                    <th>Tarefa finalizada?</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var tarefas in Model)
                {
                    <tr>
                        <td>@tarefas.Titulo</td>
                        <td>@tarefas.Descricao</td>
                        <td>@tarefas.Data.ToShortDateString()</td>
                        <td>@tarefas.hora_inicio.ToShortTimeString()</td>
                        <td>@tarefas.hora_fim.ToShortTimeString()</td>
                        <td>@tarefas.Prioridade</td>
                        <td>@tarefas.FinalizadaComoTexto</td>

                        <td>
                            <a asp-action="Editar" asp-controller="Agenda" asp-route-id="@tarefas.Id"><span><i class="fa fa-pencil"></i></span></a>
                            <a asp-action="Excluir" asp-controller="Agenda" asp-route-id="@tarefas.Id" onclick="return window.confirm('Você tem certeza que deseja deletar esta tarefa?')"><span><i class="fa-solid fa-trash-can"></i></span></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {

        <a class="btn btn-primary" asp-action="criar" asp-controller="Agenda">Nova Tarefa</a>
        <a class="btn btn-primary" asp-action="estatistica" asp-controller="Agenda">Minhas Estatísticas</a>
        <p>Nenhuma tarefa encontrada.</p>
    }
</div>

Agenda/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Agenda</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Agenda - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>